
export const citiesData = [
    {key: 'Cairo', label: 'Cairo', value: 'Cairo'},
    {key: 'Alexandria', label: 'Alexandria', value: 'Alexandria'},
    {key: 'Giza', label: 'Giza', value: 'Giza'},
    {key: 'Shubra el-Khema', label: 'Shubra el-Khema', value: 'Shubra el-Khema'},
    {key: 'Port Said', label: 'Port Said', value: 'Port Said'},
    {key: 'Suez', label: 'Suez', value: 'Suez'},
    {key: 'El Mahalla el Kubra', label: 'El Mahalla el Kubra', value: 'El Mahalla el Kubra'},
    {key: 'El Mansoura', label: 'El Mansoura', value: 'El Mansoura'},
    {key: 'Tanta', label: 'Tanta', value: 'Tanta'},
    {key: 'Asyut', label: 'Asyut', value: 'Asyut'},
    {key: 'Fayoum', label: 'Fayoum', value: 'Fayoum'},
    {key: 'Ismailia', label: 'Ismailia', value: 'Ismailia'},
    {key: 'Khusus', label: 'Khusus', value: 'Khusus'},
    {key: 'Aswan', label: 'Aswan', value: 'Aswan'},
    {key: 'Damanhur', label: 'Damanhur', value: 'Damanhur'},
    {key: 'El-Minya', label: 'El-Minya', value: 'El-Minya'},
    {key: 'Damietta', label: 'Damietta', value: 'Damietta'},
    {key: 'Luxor', label: 'Luxor', value: 'Luxor'},
    {key: 'Qena', label: 'Qena', value: 'Qena'},
    {key: 'Beni Suef', label: 'Beni Suef', value: 'Beni Suef'},
    {key: 'Sohag', label: 'Sohag', value: 'Sohag'},
    {key: 'Hurghada', label: 'Hurghada', value: 'Hurghada'},
    {key: 'Banha', label: 'Banha', value: 'Banha'},
    {key: 'Kafr al-Sheikh', label: 'Kafr al-Sheikh', value: 'Kafr al-Sheikh'},
    {key: 'Marsa Matruh', label: 'Marsa Matruh', value: 'Marsa Matruh'},
    {key: 'Kafr el-Dawwar', label: 'Kafr el-Dawwar', value: 'Kafr el-Dawwar'},
];


export const  CategoriesOptions =[
    {key: 'Food', label: 'Food', value: 'Food'},
    {key: 'Vlogger', label: 'Vlogger', value: 'Vlogger'},
    {key: 'Travel', label: 'Travel', value: 'Travel'},
    {key: 'Education', label: 'Education', value: 'Education'},
    {key: 'Sport', label: 'Sport', value: 'Sport'},
    {key: 'Music', label: 'Music', value: 'Music'},
    {key: 'Dance', label: 'Dance', value: 'Dance'},
    {key: 'Health', label: 'Health', value: 'Health'},
    {key: 'Art', label: 'Art', value: 'Art'},
    {key: 'Film', label: 'Film', value: 'Film'},
]
